name: Run pkg-config cross-platform

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - Windows
          - Linux
          - macOS
        include:
          - platform: Windows
            os: windows-latest
            # version says 0.26
          - platform: Linux
            os: ubuntu-latest
            # claim version option not supported
          - platform: macOS
            os: macos-latest
            # claim version option not supported
    steps:
      - name: Get pkg-config version and output help info
        run: |
          pkg-config -h
      - name: Test pkg-config output (default)
        run: |
          pkg-config libcrypto --libs
          pkg-config libpng --libs
          pkg-config libjpeg --libs
      - name: Test pkg-config output (--msvc-syntax)
        run: |
          pkg-config libcrypto --libs --msvc-syntax
          pkg-config libpng --libs --msvc-syntax
          pkg-config libjpeg --libs --msvc-syntax
